name: pypsa-eur
channels:
  - bioconda
  - gurobi
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affine=2.4.0
  - alsa-lib=1.2.8
  - amply=0.1.5
  - appdirs=1.4.4
  - arrow-cpp=11.0.0
  - asttokens=2.2.1
  - atlite=0.2.11
  - attr=2.5.1
  - attrs=23.1.0
  - aws-c-auth=0.6.26
  - aws-c-cal=0.5.26
  - aws-c-common=0.8.17
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.20
  - aws-c-http=0.7.7
  - aws-c-io=0.13.21
  - aws-c-mqtt=0.8.6
  - aws-c-s3=0.2.8
  - aws-c-sdkutils=0.1.9
  - aws-checksums=0.1.14
  - aws-crt-cpp=0.19.9
  - aws-sdk-cpp=1.10.57
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.12.2
  - blosc=1.21.3
  - bokeh=3.1.1
  - boost-cpp=1.78.0
  - bottleneck=1.3.7
  - branca=0.6.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.5.7
  - cairo=1.16.0
  - cartopy=0.21.1
  - cdsapi=0.6.1
  - certifi=2023.5.7
  - cffi=1.15.1
  - cfgrib=0.9.10.3
  - cfitsio=4.2.0
  - cftime=1.6.2
  - charset-normalizer=3.1.0
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.2.1
  - coin-or-cbc=2.10.10
  - coin-or-cgl=0.60.7
  - coin-or-clp=1.17.8
  - coin-or-osi=0.108.8
  - coin-or-utils=2.11.9
  - coincbc=2.10.10
  - colorama=0.4.6
  - configargparse=1.5.3
  - connection_pool=0.0.3
  - contourpy=1.0.7
  - country_converter=1.0.0
  - cryptography=40.0.2
  - curl=8.0.1
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2023.4.1
  - dask-core=2023.4.1
  - datrie=0.8.2
  - dbus=1.13.6
  - decorator=5.1.1
  - deprecation=2.1.0
  - descartes=1.1.0
  - distributed=2023.4.1
  - distro=1.8.0
  - docutils=0.20
  - dpath=2.1.5
  - eccodes=2.29.0
  - entsoe-py=0.5.8
  - et_xmlfile=1.1.0
  - exceptiongroup=1.1.1
  - executing=1.2.0
  - expat=2.5.0
  - fftw=3.3.10
  - filelock=3.12.0
  - findlibs=0.0.5
  - fiona=1.9.3
  - folium=0.14.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.39.4
  - freeglut=3.2.2
  - freetype=2.12.1
  - freexl=1.0.6
  - fsspec=2023.5.0
  - gdal=3.6.3
  - geographiclib=1.52
  - geojson-rewind=1.0.2
  - geopandas=0.13.0
  - geopandas-base=0.13.0
  - geopy=2.3.0
  - geos=3.11.1
  - geotiff=1.7.1
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - gitdb=4.0.10
  - gitpython=3.1.31
  - glib=2.76.2
  - glib-tools=2.76.2
  - glog=0.6.0
  - graphite2=1.3.13
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.33
  - gurobi=10.0.1
  - harfbuzz=6.0.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - humanfriendly=10.0
  - icu=70.1
  - idna=3.4
  - importlib-metadata=6.6.0
  - importlib_metadata=6.6.0
  - importlib_resources=5.12.0
  - iniconfig=2.0.0
  - ipython=8.13.2
  - jack=1.9.22
  - jasper=4.0.0
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - json-c=0.16
  - jsonschema=4.17.3
  - jupyter_core=5.3.0
  - kealib=1.5.0
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230125.0
  - libaec=1.0.6
  - libarrow=11.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.0.1
  - libdb=6.2.32
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgdal=3.6.3
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.76.2
  - libglu=9.0.0
  - libgomp=12.2.0
  - libgoogle-cloud=2.8.0
  - libgpg-error=1.46
  - libgrpc=1.54.2
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libnetcdf=4.9.1
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libnuma=2.0.16
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.2
  - libprotobuf=3.21.12
  - librttopo=1.1.0
  - libsndfile=1.2.0
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.41.2
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=253
  - libthrift=0.18.1
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=253
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzip=1.9.2
  - libzlib=1.2.13
  - linopy=0.1.5
  - locket=1.0.0
  - lxml=4.9.2
  - lz4=4.3.2
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.5.0
  - markupsafe=2.1.2
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - memory_profiler=0.61.0
  - mpg123=1.31.3
  - msgpack-python=1.0.5
  - munch=2.5.0
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - nbformat=5.8.0
  - ncurses=6.3
  - netcdf4=1.6.3
  - networkx=3.1
  - nomkl=1.0
  - nspr=4.35
  - nss=3.89
  - numexpr=2.8.4
  - numpy=1.23.5
  - openjdk=17.0.3
  - openjpeg=2.5.0
  - openpyxl=3.1.2
  - openssl=3.1.0
  - orc=1.8.3
  - packaging=23.1
  - pandas=2.0.1
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - partd=1.4.0
  - patsy=0.5.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.5.0
  - pip=23.1.2
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - plac=1.3.5
  - platformdirs=3.5.0
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.7.0
  - poppler=23.03.0
  - poppler-data=0.4.12
  - postgresql=15.2
  - powerplantmatching=0.5.6
  - progressbar2=4.2.0
  - proj=9.1.1
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulp=2.7.0
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - pure_eval=0.2.2
  - pyarrow=11.0.0
  - pycountry=22.3.5
  - pycparser=2.21
  - pygments=2.15.1
  - pyomo=6.5.0
  - pyopenssl=23.1.1
  - pyparsing=3.0.9
  - pyproj=3.5.0
  - pypsa=0.23.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.19.3
  - pyshp=2.3.1
  - pysocks=1.7.1
  - pytables=3.7.0
  - pytest=7.3.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - python-eccodes=1.5.1
  - python-fastjsonschema=2.16.3
  - python-tzdata=2023.3
  - python-utils=3.5.2
  - python_abi=3.11
  - pytz=2023.3
  - pyxlsb=1.0.10
  - pyyaml=6.0
  - qt-main=5.15.8
  - rasterio=1.3.6
  - re2=2023.02.02
  - readline=8.2
  - requests=2.29.0
  - reretry=0.11.8
  - rioxarray=0.14.1
  - rtree=1.0.1
  - s2n=1.3.42
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - setuptools=67.7.2
  - setuptools-scm=7.1.0
  - setuptools_scm=7.1.0
  - shapely=1.8.5
  - sip=6.7.9
  - six=1.16.0
  - smart_open=6.3.0
  - smmap=3.0.5
  - snakemake-minimal=7.25.3
  - snappy=1.1.10
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - sqlite=3.41.2
  - stack_data=0.6.2
  - statsmodels=0.14.0
  - stopit=1.1.2
  - tabula-py=2.6.0
  - tabulate=0.9.0
  - tblib=1.7.0
  - threadpoolctl=3.1.0
  - throttler=1.2.1
  - tiledb=2.13.2
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - toposort=1.10
  - tornado=6.3
  - tqdm=4.65.0
  - traitlets=5.9.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzcode=2023c
  - tzdata=2023c
  - ucx=1.14.0
  - unidecode=1.3.6
  - urllib3=1.26.15
  - validators=0.20.0
  - wcwidth=0.2.6
  - wheel=0.40.0
  - wrapt=1.15.0
  - xarray=2023.4.2
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xerces-c=3.2.4
  - xkeyboard-config=2.38
  - xlrd=2.0.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xyzservices=2023.2.0
  - xz=5.2.6
  - yaml=0.2.5
  - yte=1.5.1
  - zict=3.0.0
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - countrycode==0.2
      - tsam==2.2.1
      - vresutils==0.3.1
